# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Perform ConvertX installation tasks
  tags:
    - setup-all
    - setup-convertx
    - install-all
    - install-convertx
  block:
    - name: Validate ConvertX configuration
      when: convertx_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/validate_config.yml"

    - name: Install ConvertX
      when: convertx_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/install.yml"

- name: Perform ConvertX uninstallation tasks
  tags:
    - setup-all
    - setup-convertx
  block:
    - name: Uninstall ConvertX
      when: not convertx_enabled | bool
      ansible.builtin.include_tasks: "{{ role_path }}/tasks/uninstall.yml"
