# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of ConvertX systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ convertx_identifier }}.service"
  register: convertx_service_stat

- when: convertx_service_stat.stat.exists | bool
  block:
    - name: Ensure ConvertX systemd service is stopped
      ansible.builtin.service:
        name: "{{ convertx_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure ConvertX systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ convertx_identifier }}.service"
        state: absent

    - name: Ensure ConvertX path does not exist
      ansible.builtin.file:
        path: "{{ convertx_base_path }}"
        state: absent
